# Generated by Django 5.1.5 on 2026-04-28 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_variant_delivery_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Servicio')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.variant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cart', 'Carrito'), ('single', ' Único')], max_length=255, verbose_name='Tipo de orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=255, verbose_name='Estado')),
                ('payment_method', models.CharField(max_length=255, verbose_name='Método de pago')),
                ('reference', models.CharField(max_length=255, verbose_name='Referencia')),
                ('phone', models.CharField(max_length=255, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('items', models.ManyToManyField(related_name='orders', to='orders.item', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
    ]
