# Generated by Django 5.1.5 on 2026-05-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='service',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant',
        ),
        migrations.AddField(
            model_name='item',
            name='item_summary',
            field=models.TextField(default=1, verbose_name='Resumen del item'),
            preserve_default=False,
        ),
    ]
