# Generated by Django 5.1.5 on 2026-05-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_item_quantity_remove_item_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado')], default='pending', max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_summary',
            field=models.TextField(verbose_name='Resumen'),
        ),
    ]
