# Generated by Django 5.1.5 on 2026-05-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_items_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto total'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_converted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto total convertido'),
        ),
    ]
