# Generated by Django 5.1.5 on 2026-05-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_total_amount_order_total_amount_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='orders/receipts/', verbose_name='Comprobante de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto total (USD)'),
        ),
    ]
