# Generated by Django 5.1.5 on 2026-05-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_receipt',
        ),
    ]
