# Generated by Django 5.2.11 on 2026-02-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
            },
        ),
    ]
