# Generated by Django 5.2.11 on 2026-02-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='services/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
