# Generated by Django 5.1.5 on 2026-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_active_service_description_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='available',
            field=models.BooleanField(default=0, verbose_name='¿Disponible?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
