# Generated by Django 5.1.5 on 2026-03-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_variant_available_variant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='delivery_type',
            field=models.CharField(choices=[('manual', 'Manual')], default=1, max_length=255, verbose_name='Tipo de entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
