# Generated by Django 5.1.5 on 2026-03-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_category_variant_delivery_type_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='delivery_method',
            field=models.CharField(choices=[('id', 'ID')], default='id', max_length=255, verbose_name='Método de entrega'),
            preserve_default=False,
        ),
    ]
