# Generated by Django 5.1.5 on 2026-05-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_variant_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='delivery_method',
            field=models.CharField(choices=[('id', 'ID'), ('internal', 'Interno')], max_length=255, verbose_name='Método de entrega'),
        ),
    ]
