# Generated by Django 5.1.5 on 2026-05-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('VE', 'VE'), ('CO', 'CO'), ('US', 'US')], max_length=5, unique=True, verbose_name='Código')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tasa')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
    ]
