# Generated by Django 5.1.5 on 2026-05-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'verbose_name': 'Tasa de Moneda', 'verbose_name_plural': '1. Tasas de Monedas'},
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='label',
            field=models.CharField(choices=[('VES', 'VES'), ('COP', 'COP'), ('USD', 'USD')], default='VES', max_length=5, verbose_name='Etiqueta'),
            preserve_default=False,
        ),
    ]
