# Generated by Django 5.1.5 on 2026-05-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_currencyrate_options_currencyrate_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
