# Generated by Django 5.1.5 on 2026-05-14 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('VE', 'VE'), ('CO', 'CO'), ('US', 'US')], max_length=5, unique=True, verbose_name='Código')),
                ('label', models.CharField(choices=[('VES', 'VES'), ('COP', 'COP'), ('USD', 'USD')], max_length=5, unique=True, verbose_name='Etiqueta')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tasa')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Tasa de Moneda',
                'verbose_name_plural': '1. Tasas de Monedas',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del método')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': '2. Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Orden')),
                ('reference', models.CharField(max_length=255, verbose_name='Referencia del pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(choices=[('VES', 'Bolívares (VES)'), ('COP', 'Pesos Colombianos (COP)'), ('USD', 'Dólares Americanos (USD)')], max_length=3, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Tasa de cambio')),
                ('amount_converted', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto convertido a USD')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del pagador')),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del pagador')),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del pagador')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('date_payment', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del pago')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': '3. Pagos Realizados',
                'ordering': ['-date_created'],
            },
        ),
    ]
