# Generated by Django 5.1.5 on 2026-05-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='currency',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('COP', 'Pesos Colombianos (COP)'), ('USD', 'Dólares Americanos (USD)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
    ]
