# Generated by Django 5.1.5 on 2026-05-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='description',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='config_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuración de campos'),
        ),
    ]
