# Generated by Django 5.1.5 on 2026-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_currency_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethodfield',
            options={'ordering': ['id'], 'verbose_name': 'Campo del método de pago', 'verbose_name_plural': 'Campos del método de pago'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer_phone',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='Comprobante de pago'),
        ),
        migrations.AlterField(
            model_name='paymentmethodfield',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Etiqueta'),
        ),
    ]
