# Generated by Django 5.1.5 on 2026-05-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
