# Generated by Django 5.1.5 on 2026-05-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodfield',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción breve'),
            preserve_default=False,
        ),
    ]
